name: nikhanton
favicon: null
layout_spectrum: 0.74759
typography_spectrum: 0.60939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.590275132629143
  lightness: 0.12496805367786057
  saturation: 0.3880777395899565
  rhythmicContrast: 0.7443717129565446
purpose:
  - name: null
    item: null
    url: null
