analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.590275
  lightness: 1
  rhythmicContrast: 0.744371
  saturation: 0.388077
cta: {}
layout_spectrum: 0.74759
name: nikhanton
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.60939
