analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#41493c'
    - '#121b0a'
    - '#c9c9bf'
    - '#6f726b'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.6875
cta: {}
layout_spectrum: 0.25266
name: nik hanton - contemporary jewellery
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.60939
