name: nikhanton
favicon: null
layout_spectrum: 0.25266
typography_spectrum: 0.60939
title: Nik Hanton - Con-temporary Jeweller and Object Maker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#41493c'
    - '#121b0a'
    - '#c9c9bf'
    - '#6f726b'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
